---
- name: Hardening hosts
  hosts: all
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  become: yes
  tags:
    - hardening

- name: Configure firewall
  hosts:
    - all
  roles:
    - geerlingguy.firewall
  become: true
  tags:
    - firewall

- name: Configure docker
  hosts:
    - all
  roles:
    - geerlingguy.docker
  become: true
  tags:
    - docker

- name: Configure remna server
  hosts:
    - central
  roles:
    - iphizic.remna-server
  become: true
  tags:
    - remna-server
    - remna

- name: Configure caddy
  hosts:
    - central
  roles:
    - caddy
  become: true
  tags:
    - caddy

- name: Configure remna node
  hosts:
    - iphizic.remna_node
  roles:
    - remna-node
  become: true
  tags:
    - remna-node
    - remna