---
- name: Hardening hosts
  hosts: all
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  become: yes
  tags:
    - hardening

- name: Configure firewall
  hosts:
    - all
  roles:
    - geerlingguy.firewall
  become: true
  tags:
    - firewall

- name: Configure docker
  hosts:
    - all
  roles:
    - geerlingguy.docker
  become: true
  tags:
    - docker

- name: Configure ztnet
  hosts:
    - main_ztnet
  roles:
    - ztnet
  become: true
  tags:
    - ztnet

- name: Configure ztnet
  hosts:
    - all
  roles:
    - zerotier
  become: true
  tags:
    - zerotier

- name: Configure caddy
  hosts:
    - main_ztnet
  roles:
    - caddy
  become: true
  tags:
    - caddy
