- name: Create remna dir
  file:
    path: "{{ caddy_install_path }}"
    owner: root
    group: root
    mode: 0700
    state: directory

- name: Create docker compose
  template:
    src: docker-compose.yaml.j2
    dest: "{{ caddy_install_path }}/docker-compose.yaml"
    owner: root
    group: root
    mode: '0600'
    
- name: Create caddyfile
  template:
    src: Caddyfile.j2
    dest: "{{ caddy_install_path }}/Caddyfile"
    owner: root
    group: root
    mode: '0644'

- name: Start compose file
  community.docker.docker_compose_v2:
    project_src: "{{ caddy_install_path }}"
    remove_orphans: true
    state: present
